### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Denzo77** [scottjw/subfact_pi_ina219#4]
Hi,

May we use this repo in our Apache licensed OpenTRV project, or could you apply an Apache of BSD license to the code?

I'm also sending this to MacroYau, who's fork we're planning on using.

Thanks,

Deniz

**Comment by scottjw** [comment]
Hi Denzo77, this is a port of the Adafruit Industries library from C++ to python and the github repo can be found here https://github.com/adafruit/Adafruit_INA219

As it is licensed under a BSD licence I will add the same to this repo.

Thanks

**Comment by Denzo77** [comment]
That would be great, thanks.

**Comment by MacroYau** [comment]
Hi @scottjw, I am thinking whether we should adopt MIT which is used in the [Python I2C library](https://github.com/adafruit/Adafruit_Python_GPIO), instead of the 3-clause BSD in the C++ INA219 library [(BSD and MIT are essentially identical, except for the 3-clause BSD includes the "no endorsement" clause, as far as I understand)](http://programmers.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license).

**Comment by scottjw** [comment]
licence.txt file added with c3a554be853ca16a0f8ab376bc0c69abaf3e0396 closing issue.
